[package]
name = "vacuumlabs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {vesion = "1.0.137", features = ["derive"]}
serde_json = "1.0.81"